# Uncomment this line to define a global platform for your project
platform :ios, '9.2'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Scenography' do
	pod 'RxSwift',    '~> 3.0'
	pod 'RxCocoa',    '~> 3.0'
	pod 'RxBlocking', '~> 3.0'

  pod 'MaterialKit', :git => 'https://github.com/faresbh/MaterialKit', :branch => "swift3"
	
	pod 'XCGLogger', '~> 4.0.0'
	
	pod 'Toaster', '~> 2.0'
	
	pod 'SwiftyJSON'

  pod 'SVProgressHUD'
  pod 'Fuzi'

end

target 'ScenographyTests' do

end

target 'ScenographyUITests' do

end

post_install do | installer |
  require 'fileutils'
  FileUtils.cp_r('Pods/Target Support Files/Pods-Scenography/Pods-Scenography-acknowledgements.plist', 'Scenography/Settings.bundle/Acknowledgements.plist', :remove_destination => true)
end
