# Uncomment this line to define a global platform for your project
platform :ios, '9.2'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Scenography' do
	pod 'RxSwift',    '~> 2.0'
	pod 'RxCocoa',    '~> 2.0'
	pod 'RxBlocking', '~> 2.0'
	
	pod 'MaterialKit', :head
	
	pod 'XCGLogger', '~> 3.2'
	
	pod 'JLToast', '~> 1.3'
	
	pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
end

target 'ScenographyTests' do

end

target 'ScenographyUITests' do

end

post_install do | installer |
  require 'fileutils'
  FileUtils.cp_r('Pods/Target Support Files/Pods-Scenography/Pods-Scenography-acknowledgements.plist', 'Scenography/Settings.bundle/Acknowledgements.plist', :remove_destination => true)
end
